// Code generated by mockery v3.0.0-alpha.0. DO NOT EDIT.

package mocks

import (
	adapter "portCaptureServer/app/adapter"

	mock "github.com/stretchr/testify/mock"
)

// SavePortsServiceInstance is an autogenerated mock type for the SavePortsServiceInstance type
type SavePortsServiceInstance struct {
	mock.Mock
}

// SavePort provides a mock function with given fields: portsStream
func (_m *SavePortsServiceInstance) SavePort(portsStream adapter.PortsStream) error {
	ret := _m.Called(portsStream)

	var r0 error
	if rf, ok := ret.Get(0).(func(adapter.PortsStream) error); ok {
		r0 = rf(portsStream)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewSavePortsServiceInstance interface {
	mock.TestingT
	Cleanup(func())
}

// NewSavePortsServiceInstance creates a new instance of SavePortsServiceInstance. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSavePortsServiceInstance(t mockConstructorTestingTNewSavePortsServiceInstance) *SavePortsServiceInstance {
	mock := &SavePortsServiceInstance{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
